// Importing global styles.
import './globals.css'

// Importing Inter font from Google.
import { Inter } from 'next/font/google'

// Initiating Inter font with 'latin' as subset.
const inter = Inter({ subsets: ['latin'] })

// Defining meta data for the app.
export const metadata = { 
  title: 'Create Next App', 
  description: 'Generated by create next app', 
  // Add more metadata as required.
  charset: 'UTF-8'
}

// RootLayout functional component definition.
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // HTML language is set as "en".
    <html lang="en">
        <meta charSet={metadata.charset} />
        <body className={inter.className}>
            {children} 
        </body>
    </html>
  )
}